name       : python-poetry-core
version    : 1.0.7
release    : 1
source     :
    - https://pypi.io/packages/source/p/poetry-core/poetry-core-1.0.7.tar.gz : 98c11c755a16ef6c5673c22ca94a3802a7df4746a0853a70b6fae8b9f5cac206
license    : MIT
component  : programming.python
summary    : Poetry PEP 517 Build Backend
description: |
    Poetry PEP 517 Build Backend
build      : |
    %python3_setup
install    : |
    %python3_install
    # poetry conflicts ...
    rm $installdir/usr/lib/python%python3_version%/site-packages/poetry/__init__.py
    rm $installdir/usr/lib/python%python3_version%/site-packages/poetry/__pycache__/__init__.cpython-310.pyc
