name       : python-poetry-core
version    : 1.6.1
release    : 3
source     :
    - https://pypi.io/packages/source/p/poetry-core/poetry_core-1.6.1.tar.gz : 0f9b0de39665f36d6594657e7d57b6f463cc10f30c28e6d1c3b9ff54c26c9ac3
license    : MIT
component  : programming.python
summary    : Poetry PEP 517 Build Backend
description: |
    Poetry PEP 517 Build Backend
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - python-attrs
    - python-packaging
    - python-tomli
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
